# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutdialog(object):
    def setupUi(self, aboutdialog):
        aboutdialog.setObjectName("aboutdialog")
        aboutdialog.resize(310, 275)
        self.textBrowser = QtWidgets.QTextBrowser(aboutdialog)
        self.textBrowser.setGeometry(QtCore.QRect(31, 31, 256, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(aboutdialog)
        QtCore.QMetaObject.connectSlotsByName(aboutdialog)

    def retranslateUi(self, aboutdialog):
        _translate = QtCore.QCoreApplication.translate
        aboutdialog.setWindowTitle(_translate("aboutdialog", "О программе"))
        self.textBrowser.setHtml(_translate("aboutdialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Конструктор заданий<br />v 0.1</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Программа для создания вариативных проверочных работ по различным предметам<br />Разработал Григорович Владимир <br /><a href=\"mailto:grigvlwork@gmail.com\"><span style=\" text-decoration: underline; color:#0000ff;\">grigvlwork@gmail.com</span></a></p></body></html>"))
