# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_work.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_save_work_form(object):
    def setupUi(self, save_work_form):
        save_work_form.setObjectName("save_work_form")
        save_work_form.resize(269, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(save_work_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(save_work_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.work_name = QtWidgets.QLineEdit(save_work_form)
        self.work_name.setObjectName("work_name")
        self.verticalLayout.addWidget(self.work_name)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(save_work_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(save_work_form)
        self.buttonBox.accepted.connect(save_work_form.accept)
        self.buttonBox.rejected.connect(save_work_form.reject)
        QtCore.QMetaObject.connectSlotsByName(save_work_form)

    def retranslateUi(self, save_work_form):
        _translate = QtCore.QCoreApplication.translate
        save_work_form.setWindowTitle(_translate("save_work_form", "Dialog"))
        self.label.setText(_translate("save_work_form", "Введите название работы"))
