# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'section.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_section_edit_form(object):
    def setupUi(self, section_edit_form):
        section_edit_form.setObjectName("section_edit_form")
        section_edit_form.resize(350, 98)
        self.verticalLayout = QtWidgets.QVBoxLayout(section_edit_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.is_root = QtWidgets.QCheckBox(section_edit_form)
        self.is_root.setObjectName("is_root")
        self.verticalLayout.addWidget(self.is_root)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(section_edit_form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.section_edit = QtWidgets.QLineEdit(section_edit_form)
        self.section_edit.setObjectName("section_edit")
        self.horizontalLayout.addWidget(self.section_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(section_edit_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(section_edit_form)
        self.buttonBox.accepted.connect(section_edit_form.accept)
        self.buttonBox.rejected.connect(section_edit_form.reject)
        QtCore.QMetaObject.connectSlotsByName(section_edit_form)

    def retranslateUi(self, section_edit_form):
        _translate = QtCore.QCoreApplication.translate
        section_edit_form.setWindowTitle(_translate("section_edit_form", "Редактирование раздела"))
        self.is_root.setText(_translate("section_edit_form", "Добавить корневым разделом"))
        self.label.setText(_translate("section_edit_form", "Название раздела"))
