# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2work.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_task_to_work(object):
    def setupUi(self, add_task_to_work):
        add_task_to_work.setObjectName("add_task_to_work")
        add_task_to_work.resize(329, 88)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_task_to_work)
        self.verticalLayout.setObjectName("verticalLayout")
        self.task_name = QtWidgets.QLabel(add_task_to_work)
        self.task_name.setObjectName("task_name")
        self.verticalLayout.addWidget(self.task_name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(add_task_to_work)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.task_amount = QtWidgets.QSpinBox(add_task_to_work)
        self.task_amount.setObjectName("task_amount")
        self.horizontalLayout.addWidget(self.task_amount)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(add_task_to_work)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(add_task_to_work)
        self.buttonBox.accepted.connect(add_task_to_work.accept)
        self.buttonBox.rejected.connect(add_task_to_work.reject)
        QtCore.QMetaObject.connectSlotsByName(add_task_to_work)

    def retranslateUi(self, add_task_to_work):
        _translate = QtCore.QCoreApplication.translate
        add_task_to_work.setWindowTitle(_translate("add_task_to_work", "Добавление задачи в работу"))
        self.task_name.setText(_translate("add_task_to_work", "TextLabel"))
        self.label.setText(_translate("add_task_to_work", "Количество задач этого типа"))
