# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_task_edit_form(object):
    def setupUi(self, task_edit_form):
        task_edit_form.setObjectName("task_edit_form")
        task_edit_form.resize(582, 482)
        self.verticalLayout = QtWidgets.QVBoxLayout(task_edit_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(task_edit_form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.task_edit = QtWidgets.QLineEdit(task_edit_form)
        self.task_edit.setObjectName("task_edit")
        self.horizontalLayout_2.addWidget(self.task_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(task_edit_form)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.condition_tab = QtWidgets.QWidget()
        self.condition_tab.setObjectName("condition_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.condition_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.condition_edit = QtWidgets.QPlainTextEdit(self.condition_tab)
        self.condition_edit.setObjectName("condition_edit")
        self.horizontalLayout_3.addWidget(self.condition_edit)
        self.tabWidget.addTab(self.condition_tab, "")
        self.variables_tab = QtWidgets.QWidget()
        self.variables_tab.setObjectName("variables_tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.variables_tab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.variables_lv = QtWidgets.QListView(self.variables_tab)
        self.variables_lv.setObjectName("variables_lv")
        self.horizontalLayout_8.addWidget(self.variables_lv)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.variables_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.var_type = QtWidgets.QComboBox(self.variables_tab)
        self.var_type.setObjectName("var_type")
        self.horizontalLayout_5.addWidget(self.var_type)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.variables_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.var_example = QtWidgets.QLineEdit(self.variables_tab)
        self.var_example.setObjectName("var_example")
        self.horizontalLayout_6.addWidget(self.var_example)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.variables_tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.case_noun = QtWidgets.QComboBox(self.variables_tab)
        self.case_noun.setObjectName("case_noun")
        self.horizontalLayout_7.addWidget(self.case_noun)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.variables_tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.range_edit = QtWidgets.QPlainTextEdit(self.variables_tab)
        self.range_edit.setObjectName("range_edit")
        self.verticalLayout_2.addWidget(self.range_edit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.variables_tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.variables_tab, "")
        self.formula_tab = QtWidgets.QWidget()
        self.formula_tab.setObjectName("formula_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.formula_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formula_edit = QtWidgets.QPlainTextEdit(self.formula_tab)
        self.formula_edit.setObjectName("formula_edit")
        self.horizontalLayout_4.addWidget(self.formula_edit)
        self.tabWidget.addTab(self.formula_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(task_edit_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(task_edit_form)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(task_edit_form.accept)
        self.buttonBox.rejected.connect(task_edit_form.reject)
        QtCore.QMetaObject.connectSlotsByName(task_edit_form)

    def retranslateUi(self, task_edit_form):
        _translate = QtCore.QCoreApplication.translate
        task_edit_form.setWindowTitle(_translate("task_edit_form", "Редактирование задачи"))
        self.label_2.setText(_translate("task_edit_form", "Название задачи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.condition_tab), _translate("task_edit_form", "Условие"))
        self.label_3.setText(_translate("task_edit_form", "Тип переменной"))
        self.label_4.setText(_translate("task_edit_form", "Пример"))
        self.label_5.setText(_translate("task_edit_form", "Падеж"))
        self.label_6.setText(_translate("task_edit_form", "Диапазон значений"))
        self.textBrowser.setHtml(_translate("task_edit_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Примеры диапазона для чисел:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">range(1, 100) - числа от 1 до 99</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">range(0, 1001, 100) - числа от 0 до 1000 с шагом 100: 0, 100, 200, 300, ...</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[1, 8, 13] - конкретные числа</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Пример диапазона для текста:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[\'Ваня\', \'Петя\', \'Рома\']</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.variables_tab), _translate("task_edit_form", "Переменные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formula_tab), _translate("task_edit_form", "Формулы"))
