# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variants.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_variants_add_form(object):
    def setupUi(self, variants_add_form):
        variants_add_form.setObjectName("variants_add_form")
        variants_add_form.resize(295, 75)
        self.verticalLayout = QtWidgets.QVBoxLayout(variants_add_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(variants_add_form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.amount_sb = QtWidgets.QSpinBox(variants_add_form)
        self.amount_sb.setObjectName("amount_sb")
        self.horizontalLayout.addWidget(self.amount_sb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(variants_add_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(variants_add_form)
        self.buttonBox.accepted.connect(variants_add_form.accept)
        self.buttonBox.rejected.connect(variants_add_form.reject)
        QtCore.QMetaObject.connectSlotsByName(variants_add_form)

    def retranslateUi(self, variants_add_form):
        _translate = QtCore.QCoreApplication.translate
        variants_add_form.setWindowTitle(_translate("variants_add_form", "Добавить варианты"))
        self.label.setText(_translate("variants_add_form", "Введите необходимое количество вариантов"))
