morse = dict()
morse['a'] = '.-'
morse['b'] = '-...'
morse['c'] = '-.-.'
morse['d'] = '-..'
morse['e'] = '.'
morse['f'] = '..-.'
morse['g'] = '--.'
morse['h'] = '....'
morse['i'] = '..'
morse['j'] = '.---'
morse['k'] = '-.-'
morse['l'] = '.-..'
morse['m'] = '--'
morse['n'] = '-.'
morse['o'] = '---'
morse['p'] = '.--.'
morse['q'] = '--.-'
morse['r'] = '.-.'
morse['s'] = '...'
morse['t'] = '-'
morse['u'] = '..-'
morse['v'] = '...-'
morse['w'] = '.--'
morse['x'] = '-..-'
morse['y'] = '-.--'
morse['z'] = '--..'
morse['1'] = '.----'
morse['2'] = '..---'
morse['3'] = '...--'
morse['4'] = '....-'
morse['5'] = '.....'
morse['6'] = '-....'
morse['7'] = '--...'
morse['8'] = '---..'
morse['9'] = '----.'
morse['0'] = '-----'
text = input().lower().split()
for word in text:
    code = list()
    for i in range(len(word)):
        code.append(morse[word[i]])
    print(' '.join(code))
